### ISSUE TITLE
Crash on bindImageAnalysis

### ISSUE THREAD

**Issue by tank777** [DeepARSDK/quickstart-android-java#32]
Fatal Exception: java.nio.BufferOverflowException
       at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
       at java.nio.ByteBuffer.put(ByteBuffer.java:732)
       at com.hinotes.ui.createvideo.CreateVideoActivity$bindImageAnalysis$1.analyze
       at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2$ImageAnalysis(ImageAnalysis.java:450)
       at androidx.camera.core.-$$Lambda$ImageAnalysis$-wcArnbkVmqkAHxpJ0VOR9b2w0Q.analyze(:4)
       at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:145)
       at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$8nmjUxCmaK9ClOx3NHAdwtp6S3w.run(:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7877)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by dreampowder** [comment]
getting the same error too.

**Comment by forec1** [comment]
This has been fixed in de9bc0fd5ec66dcdcecbb4c82399f16a5dadbc3f. 
Note however that the preferred way of sending camera frames to the DeepAR is through [receiveFrameExternalTexture](https://s3.eu-west-1.amazonaws.com/sdk.developer.deepar.ai/doc/android/ai/deepar/ar/DeepAR.html#receiveFrameExternalTexture-int-int-int-boolean-int-).
