### ISSUE TITLE
 Unable to update texture contents

### ISSUE THREAD

**Issue by tuananhdtu** [DeepARSDK/quickstart-android-java#34]
2021-12-22 08:31:08.474 5969-5969/ai.deepar.deepar_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.deepar.deepar_example, PID: 5969
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at ai.deepar.deepar_example.ARSurfaceProvider.lambda$onSurfaceRequested$0$ARSurfaceProvider(ARSurfaceProvider.java:66)
        at ai.deepar.deepar_example.-$$Lambda$ARSurfaceProvider$JAipkCmqGxwLcfXLPwXbYnzYXAQ.onFrameAvailable(Unknown Source:4)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by tuananhdtu** [comment]
My device SM-J410f not use useExternalCameraTexture = true, when i set to false, camera will open but laggy

**Comment by tuananhdtu** [comment]
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:291)
        at java.nio.ByteBuffer.put(ByteBuffer.java:642)
        at ai.deepar.deepar_example.MainActivity$12.analyze(MainActivity.java:468)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:367)

**Comment by JelenaKB** [comment]
Sorry, using external textures is an optional optimization for newer devices that we demoed in our quickstart example, some older devices will, unfortunately, crash from this. If you are unsure if the device in question supports external textures you should be able to easily disable them
﻿

https://github.com/DeepARSDK/quickstart-android-java/blob/master/app/src/main/java/ai/deepar/deepar_example/MainActivity.java


﻿If you are using the code from our quickstart you can just set
﻿
﻿useExternalCameraTexture = false;

as you have.

The lag will change depending on the selected effect, some effects are more processor intensive than others.
